# config/packages/security.yaml
security:
    enable_authenticator_manager: true
    providers:
        in_memory: { memory: null }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: in_memory
            json_login:
                check_path: /login
                username_path: email
                password_path: password
            logout:
                path: /logout
                target: /
            jwt:
                pattern: ^/api
                stateless: true
                jwt: ~
    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }